// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNShZTBmsn_Ok5opPNCK14ULFnPQMMcc',
    appId: '1:413116602762:web:2f9572b766d26af0701073',
    messagingSenderId: '413116602762',
    projectId: 'eng-gate-453810-h3',
    authDomain: 'eng-gate-453810-h3.firebaseapp.com',
    storageBucket: 'eng-gate-453810-h3.firebasestorage.app',
    measurementId: 'G-PMRY7ZKMP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYWTsbup48pcQy3_7fqqUkiXY93cMhSI',
    appId: '1:413116602762:android:18ff9d63b2fab89b701073',
    messagingSenderId: '413116602762',
    projectId: 'eng-gate-453810-h3',
    storageBucket: 'eng-gate-453810-h3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zMVFooElwQUaKuLkrXWWxqash4z5bTA',
    appId: '1:413116602762:ios:eae85d3f0e804a0d701073',
    messagingSenderId: '413116602762',
    projectId: 'eng-gate-453810-h3',
    storageBucket: 'eng-gate-453810-h3.firebasestorage.app',
    iosClientId: '413116602762-bsot6d0l32d2tsd70vgimrf1p4fn3vss.apps.googleusercontent.com',
    iosBundleId: 'com.yellowstonelogisticsllcsapplication.app.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4zMVFooElwQUaKuLkrXWWxqash4z5bTA',
    appId: '1:413116602762:ios:beb949d960bd96c6701073',
    messagingSenderId: '413116602762',
    projectId: 'eng-gate-453810-h3',
    storageBucket: 'eng-gate-453810-h3.firebasestorage.app',
    iosClientId: '413116602762-1eimfcq2a6i5nqqi76cfaatuu5khjo8m.apps.googleusercontent.com',
    iosBundleId: 'com.yellowstonelogisticsllcsapplication.yellowstoneLogisticsLlcSApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZNShZTBmsn_Ok5opPNCK14ULFnPQMMcc',
    appId: '1:413116602762:web:965a138f478b3938701073',
    messagingSenderId: '413116602762',
    projectId: 'eng-gate-453810-h3',
    authDomain: 'eng-gate-453810-h3.firebaseapp.com',
    storageBucket: 'eng-gate-453810-h3.firebasestorage.app',
    measurementId: 'G-NRQBHYLCXN',
  );
}
